version: "2"
services:
  python:
    image: python/flask:latest
    ports:
      - "5000:5000"
    volumes:
      - /Users/emiliano/Documents/docker_flask:/home/emiliano/work
    links:
      - base_datos
    tty: true
  base_datos:
    image: mongo:3.4.4
    ports:
      - "26017:27017"
      - "25017:28017"
